import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/core/Sidebar";
import Header from "@/components/core/Header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="flex h-screen font-sans bg-gray-100">
          <div className="no-print">
            <Sidebar />
          </div>
          <div
            className="removesidebarspace flex-1 flex flex-col ml-[15%]"
            style={{ width: "calc(100vw - 30%)" }}
          >
            <div className="no-print">
              <Header />
            </div>

            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
